# Generated by Django 4.2.23 on 2025-12-05 07:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source_type', models.CharField(choices=[('META_ADS', 'Facebook/Instagram Ads'), ('CHAT', 'AskRivo Chat'), ('OTHER', 'Other')], max_length=50)),
                ('lifecycle_state', models.CharField(choices=[('INCUBATION', 'Incubation - Testing'), ('LIVE', 'Live - Production'), ('QUARANTINE', 'Quarantine - Paused')], default='INCUBATION', max_length=20)),
                ('total_leads', models.IntegerField(default=0)),
                ('valid_leads', models.IntegerField(default=0)),
                ('spam_leads', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must contain at least 10 digits', regex='^\\+?\\d{10,}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('intent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('SPAM', 'Spam')], default='PENDING', max_length=20)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.source')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='leads_rawle_phone_497ab4_idx'), models.Index(fields=['status'], name='leads_rawle_status_796dbe_idx'), models.Index(fields=['assigned_to'], name='leads_rawle_assigne_6fd5db_idx')],
            },
        ),
    ]
