# Generated by Django 4.2.23 on 2025-12-06 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_rawlead_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawlead',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='rawlead',
            index=models.Index(fields=['assigned_by'], name='leads_rawle_assigne_2b32bb_idx'),
        ),
    ]
