# Generated by Django 4.2.23 on 2025-12-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_rawlead_creation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawlead',
            name='note',
            field=models.TextField(blank=True, help_text='Note added when marking lead as valid/spam', null=True),
        ),
    ]
