# Generated by Django 4.2.23 on 2025-12-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_rawlead_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('META_ADS', 'Facebook Ads'), ('INSTA_ADS', 'Instagram Ads'), ('WHATSAPP_ADS', 'WhatsApp Ads'), ('CHAT', 'AskRivo Chat'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
