# Generated by Django 4.2.23 on 2025-12-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_add_whatsapp_insta_source_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawlead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='When the lead was assigned', null=True),
        ),
    ]
