# Generated by Django 4.2.23 on 2025-12-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_add_assigned_at_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rawlead',
            name='leads_rawle_assigne_2b32bb_idx',
        ),
        migrations.AlterField(
            model_name='rawlead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
