# Generated by Django 4.2.23 on 2025-12-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_simplify_assignment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('META_ADS', 'Facebook Ads'), ('INSTA_ADS', 'Instagram Ads'), ('WHATSAPP_ADS', 'WhatsApp Ads'), ('CHAT', 'AskRivo Chat'), ('PARTNER_HUB', 'Partner Hub'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='rawlead',
            index=models.Index(fields=['assigned_by'], name='leads_rawle_assigne_2b32bb_idx'),
        ),
        migrations.AddIndex(
            model_name='rawlead',
            index=models.Index(fields=['assigned_at'], name='leads_rawle_assigne_847ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='rawlead',
            index=models.Index(fields=['source', 'status'], name='leads_rawle_source__3ed66c_idx'),
        ),
    ]
