# Generated by Django 4.2.23 on 2025-12-07 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0008_alter_source_source_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('current_stage', models.CharField(choices=[('LEAD_IN', 'Lead In'), ('QUALIFIED', 'Qualified'), ('PROCESSING', 'Processing'), ('SUBMITTED', 'Submitted'), ('DISBURSED', 'Disbursed'), ('LOST', 'Lost'), ('REJECTED', 'Rejected')], db_index=True, default='LEAD_IN', max_length=50)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_files', to=settings.AUTH_USER_MODEL)),
                ('raw_lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='file', to='leads.rawlead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentityAtom',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='identity', serialize=False, to='files.file')),
                ('full_legal_name', models.CharField(blank=True, max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('emirates_id', models.CharField(blank=True, max_length=20)),
                ('residency_status', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
