# Generated by Django 4.2.23 on 2025-12-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='assigned_to',
        ),
    ]
