# Generated by Django 4.2.23 on 2025-12-07 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_remove_file_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_stage', models.CharField(blank=True, choices=[('LEAD_IN', 'Lead In'), ('QUALIFIED', 'Qualified'), ('PROCESSING', 'Processing'), ('SUBMITTED', 'Submitted'), ('DISBURSED', 'Disbursed'), ('LOST', 'Lost'), ('REJECTED', 'Rejected')], max_length=50, null=True)),
                ('to_stage', models.CharField(choices=[('LEAD_IN', 'Lead In'), ('QUALIFIED', 'Qualified'), ('PROCESSING', 'Processing'), ('SUBMITTED', 'Submitted'), ('DISBURSED', 'Disbursed'), ('LOST', 'Lost'), ('REJECTED', 'Rejected')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='files.file')),
            ],
            options={
                'verbose_name_plural': 'Stage histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
