# Generated by Django 4.2.23 on 2025-12-07 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_add_stage_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StageHistory',
            new_name='FileHistory',
        ),
        migrations.AlterModelOptions(
            name='filehistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'File histories'},
        ),
        migrations.AlterModelTable(
            name='filehistory',
            table='files_filehistory',
        ),
        migrations.AlterField(
            model_name='filehistory',
            name='file',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='history',
                to='files.file',
            ),
        ),
    ]